[package]
name = "fo_proto_format"
version = "0.3.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
cini = "1.0"
serde = { version="1", features=["derive"] }
serde_json = "1"
toml = "0.8.0"
